### ISSUE TITLE
"%unnumbered" option attribute isn't working in OGC flavour.

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-ogc#13]
The exclusion from auto-numbering is not being achieved in OGC flavour.

Sample markup:
````
== First Section
Random text

[%unnumbered]
=== This section title should not be numbered
Random text
````
HTML output:
![capture1](https://user-images.githubusercontent.com/33627611/72404596-3fff3500-372c-11ea-8d8f-e221d1f290f6.JPG)

Sample file: 
[ogc-uissue.zip](https://github.com/metanorma/mn-samples-ogc/files/4063050/ogc-uissue.zip)

**Comment by opoudjis** [comment]
The `%unnumbered` option does not work with section numbers at all, it only works with assets like tables and figures. We actually do not have any option to suppress numbering for a particular header.

I can implement `%unnumbered`, but I'd like discussion first on whether it is a good idea. Referencability of every sentence in a document via a hierarchy of headings is a very important principle, and I'm reluctant to sacrifice it. (Asciidoctor has a notion of floating titles, https://asciidoctor.org/docs/user-manual/#discrete-headings, to allow unnumbered titles.)

@manuel489 could you show me the original document, so I can understand better what is expected here?

**Comment by manuelfuenmayor** [comment]
Thanks @opoudjis ! 
I thought I remembered using the `%unnumbered` option to remove a title number. 
Also, I felt motivated to open this ticket when I got an unwanted numbered table (using the `%unnumbered` option). Then, I realized I was using the wrong structure markup. I mean, for example, for a random table I had put the following options:

````
[cols="2",options="header",%unnumbered]
|===
...
|===
````

This didn't work on removing the table numbering. However, if I put it like this:

````
[%unnumbered]
[cols="2",options="header"]
|===
...
|===
````
It works properly. Therefore, I think there is nothing to solve here. We can close this issue.

Thank you!

**Comment by opoudjis** [comment]
OK, so, to confirm:

Option markup is somewhat opaque, the option apparently needs to be the first in the list of attributes.

Section numbers skipping numbers (floating titles) can be implemented, but as you know, that breaks the strict hierarchy that is so important for precise cross-referencing in Metanorma (being about standards documents), and usually is not appropriate: the instance you had requested, where "Chapter 1" and "title" were separated by carriage return, is better handled by inserting a carriage return in the "Chapter" number that would be inserted before the section title.

If you do not currently need a true floating title in OGC, then I am closing this. (And if you do, I'll be earnestly looking for workarounds anyway.)
