### ISSUE TITLE
Code-blocks get numbered as if they were figures (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-ogc#14]
This issue alters the numbering order of the actual figures (in any output).

**Code-block sample:**
````
== Code-block sample
----
1 <xsd:complexType name="LanguageStringType">
2   <xsd:simpleContent>
3       <xsd:extension base="string">
4           <xsd:attribute ref="xml:lang" use="optional"/>
5           <!-- ... additional optional attributes ... --!>
5       </xsd:extension>
6   </xsd:simpleContent>
7 </xsd:complexType>
----
````
**DOC output:**
![capture2](https://user-images.githubusercontent.com/33627611/72405774-67f09780-3730-11ea-8685-6fc76b22c352.JPG)

File sample: 
[ogc-cissue.zip](https://github.com/metanorma/mn-samples-ogc/files/4063111/ogc-cissue.zip)

**Comment by opoudjis** [comment]
So here's the thing. We have decided to number source code as a result of https://github.com/metanorma/isodoc/issues/156. We are currently numbering them as figures, because that would look less disruptive than the alternative. But that would inevitably distort any figure numbering you are trying to replicate.

I think the easiest solution to take here is to exclude sourcecode from numbering, via the `%unnumbered` option. It may be that instead, I should not conflate sourcecode with figures, but number them as a distinct sequence of assets. @ronaldtse, @manuel489, suggestions welcome.

**Comment by ronaldtse** [comment]
I think Figure numbering is correct. However, maybe `sourcecode` isn't always a figure?

Or we use syntax like `[%source]` to indicate it's not numbered?

**Comment by manuelfuenmayor** [comment]
I agree with @ronaldtse , I think Figure numbering is just fine. I've seen books that include source code blocks with Figure numbering (e.g. Tanenbaum's Computer Networks). 

Also, I think that @ronaldtse 's suggestion about `[%source]` would be more elegant in comparison with `[%unnumbered]`. (Well, it's just a markup detail :smile: )

Now, it is worth to mention that, currently, the code-block numbering is visible in .doc output only (not in HTML).

Thanks @opoudjis , I will use `%unnumbered` to workaround this issue 👍 .

**Comment by ronaldtse** [comment]
> Tanenbaum's Computer Networks

That was one of my favorite books in college!!

**Comment by manuelfuenmayor** [comment]
@ronaldtse I like it too :metal: ! Even though I haven't read it entirely.

**Comment by opoudjis** [comment]
I would rather keep `[%unnumbered]` consistent in the meaning of "omit from numbering" no matter what the context.

The fact that the numbering is restricted to DOC and not in HTML is bad news. Checking.

**Comment by opoudjis** [comment]
Yes, I was only inserting title in the HTML version of the rendering of sourcecode if a name was present; that condition no longer obtains. Moreover, the title was being inserted within the preformatted block, which is wrong.

**Comment by opoudjis** [comment]
Addressed discrepancy
