### ISSUE TITLE
Issues with 08-062r7

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#22]
Issues to be handled in markup or metanorma-ogc:

- Unlike the other OGC documents, this one doesn't have submission, approval and publication date, rather only "Date". There are also no editors listed. I'm not sure how this should be solved in adoc.
- Warning on the front page has a different content, as well as the License Agreement.
- [class=steps] is not working.
- Header and footer in the generated .doc should have a different content.
- Text is not justified in the generated .doc file.
- Years are missing in the quotes.

**Comment by opoudjis** [comment]
See https://github.com/metanorma/mn-samples-ogc/issues/21 for:

> [class=steps] is not working.
> Warning on the front page has a different content, as well as the License Agreement.
> Header and footer in the generated .doc should have a different content.

**Comment by opoudjis** [comment]
> Unlike the other OGC documents, this one doesn't have submission, approval and publication date, rather only "Date". There are also no editors listed. I'm not sure how this should be solved in adoc.

We are going to keep the three dates mandatory, rather than encourage laxity: just copy the date of publication across to the other two, that's expedient.

(It's incorrect? Sure. And it's OGC's responsibility to fix it in future: they are meant to have those dates on file.)

On the other hand, editors are optional in HTML, and mandatory in Word: I will make them optional in Word too, since documents without named editors (as corporate publications of OGC) are conceivable.

**Comment by opoudjis** [comment]
> Text is not justified in the generated .doc file.

No OGC text is justified; and justification needs to be applied consistently—either all or none. @ronaldtse Please escalate.

**Comment by opoudjis** [comment]
> Years are missing in the quotes.

@anermina What are you referring to? 

> he OGC approach to feature modeling follows the principles specified in ISO 19109:2005, “Geographic information — Rules for application schema.” 

The years are preserved in there; and i don't see any obvious quotes other than those in http://rap.opengeospatial.org/orm.php

**Comment by opoudjis** [comment]
Putting on hold pending escalation and clarifications

**Comment by ronaldtse** [comment]
> Text is not justified in the generated .doc file.

Regarding this, it is now clarified in metanorma/metanorma-ogc#98 that text should always be "left justified".

**Comment by opoudjis** [comment]
Remaining clarification is from @anermina re Years and Quotes.

**Comment by anermina** [comment]
Dates are added in #50. 

> Years are missing in the quotes.

At the end of the original document, there are two quotes/citations, which I wasn't sure how to produce in .adoc. Can you please let me know how to properly make this?

Original:
![image](https://user-images.githubusercontent.com/55683568/75918862-c696df80-5e5c-11ea-800c-39c8670de5a5.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/75918921-e62e0800-5e5c-11ea-8fa4-863fd1f39caa.png)

In .adoc, I wrote those as follows:
[quote, Jerome K Jerome, 1886]
We are so bound together that no man can labor for himself alone. Each blow he strikes in his own behalf helps to mold the Universe.

[quote, William James, 1890]
Wisdom is knowing what to leave out

**Comment by opoudjis** [comment]
@anermina Oh! That's easy:

`[quote, "Jerome K Jerome, 1886"]`

The quotes override the commas, which in that context introduce a separate argument.

**Comment by anermina** [comment]
Perfect, thank you!

Change is added in #59
