### ISSUE TITLE
Inconsistency with 10-100r3 document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#23]
From @manuel489  in #16 :

In the original document, there are several titles that shouldn't be part of the main content as they are part of the "front material" of the doc. That means, they should get numbered with Roman numerals (i., ii., iii., ..., etc). These titles are: Document terms and definitions, Document contributor contact points, Changes to the OpenGIS(R) Abstract Specification, Changes to existing Implementation Standards, and Future Work.

However, as instructed by OGC, the prefix sections are fixed. We will need to address this.

**Comment by ronaldtse** [comment]
Related to https://github.com/metanorma/metanorma-ogc/issues/61

**Comment by ronaldtse** [comment]
This behavior is confirmed by OGC here: https://github.com/metanorma/metanorma-ogc/issues/68 . 

This ticket is to see how to adjust for previous documents.

**Comment by opoudjis** [comment]
@ronaldtse This has been addressed by https://github.com/metanorma/metanorma-ogc/issues/83, right?

If so, @manuel489 is to action propagating that solution to the documents affected.

**Comment by manuelfuenmayor** [comment]
I think @opoudjis has right. I have added the `[.preface]` attribute where is needed. Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse , I think this is already solved, right?

**Comment by ronaldtse** [comment]
Yup. Thanks!
