### ISSUE TITLE
Re-enable processing of 18-046 in `metanorma.yml` when metanorma/metanorma-standoc#200 is fixed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#24]
Re-enable processing of 18-046 in `metanorma.yml` when metanorma/metanorma-standoc#200 is fixed.

All you have to do is to revert ac2e5bc37a5933b74b6294b254c085da2cf9db53.

**Comment by opoudjis** [comment]
Already reverted.

Please respect my time.
