### ISSUE TITLE
Differences of 00-027 with original

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#28]
Differences between the original and the generated document:
- Style of the front page is different. Only release date is given in the original document (no submission/approval/publication date).
- Instead of the License Agreement, which is included in the generated document, the original contains Notice.
- List of Figures is included in the generated document, unlike in the original.
- The first section (Preface) is numbered with 0 in the original document and with 1 in the generated document.
- Header and footer content is different.
- I'm not sure whether the page break should be added in .adoc after each section, or it should be set as a general rule that each section starts on a new page. Please let me know if I should add page breaks.
- In the original document, figures and their captions are left-aligned, while they are centered in the generated document (which I believe is good).
- [class=steps] is not working in OGC.
- In cross-references, generated document uses the word "Clause", while the original document uses "section".
- [appendix,obligation=informative] produces the title "Annex", while "Appendix" is expected.

Originally from #25 .

**Comment by opoudjis** [comment]
This spec is 20 years old, and the following discrepancies, I would argue, should not be addressed: they would be a non-trivial amount of customisation (only some of which can be done via configuration), for an edge case.

> Style of the front page is different. Only release date is given in the original document (no submission/approval/publication date).

> Instead of the License Agreement, which is included in the generated document, the original contains Notice.

(A new boilerplate XML could be generated to put the text specific to this version of OGC, but I do not believe it is worthwhile.)

> List of Figures is included in the generated document, unlike in the original.

> The first section (Preface) is numbered with 0 in the original document and with 1 in the generated document.

> In the original document, figures and their captions are left-aligned, while they are centered in the generated document (which I believe is good).

> In cross-references, generated document uses the word "Clause", while the original document uses "section".

> [appendix,obligation=informative] produces the title "Annex", while "Appendix" is expected.

The following are known issues from https://github.com/metanorma/mn-samples-ogc/issues/21

> Header and footer content is different.

> [class=steps] is not working in OGC.

**Comment by opoudjis** [comment]
> I'm not sure whether the page break should be added in .adoc after each section, or it should be set as a general rule that each section starts on a new page. Please let me know if I should add page breaks.

This is a completely differently formatted document, and page breaks used to be the rule back in 2000; it is not now. I do not believe that reproducing the 2000 formatting in the current flavour is worthwhile: I would not insert page breaks.

**Comment by opoudjis** [comment]
Putting on hold, with recommendation to close.

**Comment by ronaldtse** [comment]
@opoudjis agree to close this one.
