### ISSUE TITLE
Deal with additional paragraphs within References in 16-114r3

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#53]
> Additional paragraphs in the References section (after the list of references) are not generated.

From @anermina https://github.com/metanorma/mn-samples-ogc/pull/39

**Comment by opoudjis** [comment]
Metanorma is strict about processing stuff in references that it deems to be extraneous: it only accepts for rendering bibitems and notes. I can relax it, but I'd need to be convinced that I should, and that this is not licensing bad markup.

**Comment by anermina** [comment]
This is References section from the original document:
![image](https://user-images.githubusercontent.com/55683568/76241308-0bdc5800-6235-11ea-8634-3544915dd9d4.png)

Text below the references list is just added after the list in .adoc, like this:
* [[[noaa,NOAA]]], NOAA: NCEI netCDF Templates – http://www.nodc.noaa.gov/data/formats/netcdf/[http://www.nodc.noaa.gov/data/formats/netcdf/]

The OGC 11-165r2 CF-netCDF standard is based on Climate and Forecast (CF) conventions version 1.6. The Attribute Convention for Data Discovery (ACDD) adds additional attributes that provide useful metadata for Catalog Service on the Web (CSW). The National Centers for Environmental Information (NCEI) document is used as a guideline when an ambiguity needs to be resolved.

**Comment by opoudjis** [comment]
OK, this has just been addressed in https://github.com/metanorma/metanorma-ogc/issues/101 . Please test with github version of isodoc.
