### ISSUE TITLE
Question on IETF bibliographic item rendering

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#61]
@anermina re: bibliographic items:

You might realize that the IETF references are "auto-fetched" (https://www.metanorma.com/author/topics/building/reference-lookup/)

(and ISO, IEC, ITU, OGC, NIST ...)

This is a manual rendering of a bibliographic item:
```adoc
* [[[openapi,Open API Initiative]]], Open API Initiative: OpenAPI Specification 3.0.2, 2018 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
```

This is an auto-fetched document, and is identical in effect to:
```adoc
* [[[rfc2616,RFC 2616]]], Fielding, R., Gettys, J., Mogul, J., Frystyk, H., Masinter, L., Leach, P., Berners-Lee, T.: IETF RFC 2616, HTTP/1.1, 1999 http://tools.ietf.org/rfc/rfc2616.txt
```
SAME AS:
```
* [[[rfc2616,RFC 2616]]]
```

Is this the difference you see?

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-ogc/pull/36#issuecomment-597271145_

**Comment by anermina** [comment]
Yes. So the question should be: Do I need to add :no-isobib: in this case to produce the same result as in the original document, or it is correct to keep currently rendered details for RFCs (keep automatic reference lookup)?

**Comment by ronaldtse** [comment]
@anermina it is correct to keep the rendered details for RFCs -- this is what we want the users to follow because automatic rendering of the references will be always correct (unless it's our bug). Overriding rendering rules should be discouraged.

That said, I think we should have some examples that use the AsciiBib format for rendering (see https://www.metanorma.com/author/ietf/topics/references/ , I wonder why this section is only in MN-IETF...).

**Comment by ronaldtse** [comment]
Done, closing.
