### ISSUE TITLE
Encode 17-069r3 requirements as metanorma requirements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#64]
From @manuel489:

> I was working on it, but I stumbled with a problem: this document contains *Conformance Class* and *Abstract Test* blocks. And I believe we don't have a proper markup for these cases. (I didn't find any documentation about it.)

To give an example of these two blocks:

*Conformance Class:*
![capture-conformance](https://user-images.githubusercontent.com/33627611/76543637-2db82380-645d-11ea-8337-3e2da2283866.PNG)

*Abstract Test:*
![capture-abstract](https://user-images.githubusercontent.com/33627611/76543783-5f30ef00-645d-11ea-9597-95e2b531e3df.PNG)

_Originally posted by @manuel489 in https://github.com/metanorma/mn-samples-ogc/pull/57#issuecomment-598286023_

This is actionable when metanorma/metanorma-ogc#110 is fixed.

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/metanorma/mn-samples-ogc/pull/69

**Comment by manuelfuenmayor** [comment]
This is done. Closing.
