### ISSUE TITLE
Questions for OGC 10-091r3

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-ogc#65]
- Terms and definitions section is given twice in this document - first in the preface, then as a regular section. Currently, both sections appear separately in the generated document, but none of them is in the preface (although I've marked the first one with [.preface] tag). Preface doesn't contain Terms and definitions by default, but here we have an exception. How should this be handled? 

Original (preface):
![image](https://user-images.githubusercontent.com/55683568/76711516-2620a500-6711-11ea-8311-d6a09f19e178.png)

Original (regular section):
![image](https://user-images.githubusercontent.com/55683568/76711527-389ade80-6711-11ea-8b22-b672ef240d81.png)

Generated :
![image](https://user-images.githubusercontent.com/55683568/76711735-b4e1f180-6712-11ea-8fa6-225d43fab67b.png)
![image](https://user-images.githubusercontent.com/55683568/76711737-bad7d280-6712-11ea-8c2a-b043e39fb1b0.png)

- Normative references section contains different description than it regularly does. I didn't add this description in .adoc, but please let me know if I should.

Original:
![image](https://user-images.githubusercontent.com/55683568/76711536-4a7c8180-6711-11ea-8442-193c32aa5515.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/76711542-5bc58e00-6711-11ea-8501-465be6b8f049.png)

- There are two references sections, as well. The first one refers to normative references, and the second one should be bibliography. The second References section (the one before the annex) couldn't be generated with the title "References" (probably because it then refers to Normative References), so I renamed it to "Bibliography". Please let me know is this a proper way of solving this issue, or something else should have been done.

**Comment by ronaldtse** [comment]
> Preface doesn't contain Terms and definitions by default, but here we have an exception. How should this be handled?

Since this is no longer allowed in the new OGC document model, all T&D must be under Clause 4. We don't need to adhere to the original clause numbering. The extra T&D section (which is empty) should be removed.

> Normative references section contains different description than it regularly does. I didn't add this description in .adoc, but please let me know if I should.

As above. This is an older document, so discrepancies are expected to give way to the newly defined rules and structure.

> There are two references sections, as well. The first one refers to normative references, and the second one should be bibliography. The second References section (the one before the annex) couldn't be generated with the title "References" (probably because it then refers to Normative References), so I renamed it to "Bibliography". Please let me know is this a proper way of solving this issue, or something else should have been done.

The method of resolution is correct!

Could you please help update #66 to reflect this? Thanks!

**Comment by anermina** [comment]
Thank you, @ronaldtse ! #66 is updated.

**Comment by ronaldtse** [comment]
Thanks @anermina ! I've also removed the reference to "OGC 10-093" because that paper was never published, and we can't reference a reference that was "supposed to be published" anyway.
