### ISSUE TITLE
Fix Windows and Linux build failures

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#68]
* Windows failure is due to https://github.com/metanorma/metanorma-build-scripts/issues/34
* Ubuntu failure is due to https://github.com/metanorma/metanorma-linux-setup/issues/23

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-ogc/pull/66#issuecomment-603319709_

**Comment by CAMOBAP** [comment]
Fixed

**Comment by ronaldtse** [comment]
Excellent, thanks @CAMOBAP795 !
