### ISSUE TITLE
Utilize common license agreement, warning and preface notes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#73]
When these tasks are completed:

* metanorma/metanorma-ogc#116
* metanorma/metanorma-ogc#117
* metanorma/metanorma-ogc#118

All samples (esp 08-062r7 as described in #22 and metanorma/metanorma-ogc#91) should be updated to utilize the common text.

**Comment by manuelfuenmayor** [comment]
@ronaldtse , I have checked the OGC outputs and they all meet with the specifications given in https://github.com/metanorma/metanorma-ogc/issues/91

Just two comments to make:
- Several docs (10-091r3, 10-100r3, 14-065r2, among others) contain duplicated Preface notes: one generated automatically, and other included by the user in the Preface area. I guess we should remove this last one, right? (I could push PR for that)
- The warning message established for *Best Practice* differs in a word from the description given.

  In https://github.com/metanorma/metanorma-ogc/issues/91: 
"This document defines an OGC Best **Practice** on a particular technology..."
  While, in the outputs:
"This document defines an OGC Best **Practices** on a particular technology..."
  
  (Maybe not a big deal?)

Thanks!

**Comment by ronaldtse** [comment]
> Several docs (10-091r3, 10-100r3, 14-065r2, among others) contain duplicated Preface notes: one generated automatically, and other included by the user in the Preface area. I guess we should remove this last one, right? (I could push PR for that)

Yes please!

> "This document defines an OGC Best Practice on a particular technology..."
While, in the outputs:
"This document defines an OGC Best Practices on a particular technology..."

It should be the first ("This document defines an OGC Best Practice on a particular technology...") since the latter one has wrong grammar.

Thanks!

**Comment by ronaldtse** [comment]
Is the warning message mistake generated automatically or manually? If automatically, it should be filed at metanorma-ogc. Thanks!

**Comment by manuelfuenmayor** [comment]
>Is the warning message mistake generated automatically or manually? If automatically, it should be filed at metanorma-ogc. Thanks!

Automatically,
![warning-capture](https://user-images.githubusercontent.com/33627611/78055514-a706b000-7351-11ea-9c40-64e6088d2fbd.JPG)

Ok!

**Comment by manuelfuenmayor** [comment]
> Is the warning message mistake generated automatically or manually? If automatically, it should be filed at metanorma-ogc. Thanks!

Ticket opened here: https://github.com/metanorma/metanorma-ogc/issues/131

**Comment by manuelfuenmayor** [comment]
@ronaldtse , @opoudjis has already solved the problem of the warning message. I think all is good now regarding this issue.

**Comment by manuelfuenmayor** [comment]
This issue is solved. Closing.
