### ISSUE TITLE
Missing references in 17-069 and 18-053r2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#74]
There are a few unresolved ID reference in the source XML documents (https://metanorma.github.io/mn-samples-ogc/):

- 17-069.xml

Unresolved ID reference "rc2616" found.
Unresolved ID reference "rc_oas" found.
Unresolved ID reference "encodings" found.

- 18-053r2.xml 

Unresolved ID reference "grids" found.
Unresolved ID reference "_BinaryBodyReference_1]" found.
Unresolved ID reference "gltf" found.
Unresolved ID reference "_glTF" found.
Unresolved ID reference "composite" found.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/issues/76#issuecomment-597282386_

**Comment by anermina** [comment]
I believe these issues are already solved, since there are no errors/warnings of this type in the outputs after generating mentioned documents now.

**Comment by ronaldtse** [comment]
That's true. Thanks!
