### ISSUE TITLE
Label issues in 17-069 and 18-046

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#76]
```
echo "Running locally..."; bundle exec metanorma documents/17-069.xml
Running locally...
nil versions are discouraged and will be deprecated in Rubygems 4
No label has been processed for ID _b44ec54d-528f-4bb4-bbc0-359f49d3762f
No label has been processed for ID rc_oas
No label has been processed for ID encodings
...
echo "Running locally..."; bundle exec metanorma documents/18-046.xml
Running locally...
nil versions are discouraged and will be deprecated in Rubygems 4
No label has been processed for ID demonstration_workshop
No label has been processed for ID kickoff_workshop
No label has been processed for ID hackaton_scenario
```

The first document is in https://github.com/metanorma/ogc-wfs where we probably don't want to update.

The second document has anchors set on paragraphs, but they're not carried to the XML.

**Comment by ronaldtse** [comment]
The second label issues are supposed to work:

```
No label has been processed for ID demonstration_workshop
No label has been processed for ID kickoff_workshop
No label has been processed for ID hackaton_scenario
```

https://github.com/metanorma/mn-samples-ogc/blob/master/sources/18-046/sections/07-appendix-a.adoc
```adoc
=== Sequence of Events, Phases, and Milestones

[[kickoff_workshop]]
*Kickoff Workshop:* A Kickoff Workshop ("Kickoff") is a face-to-face meeting with the option to attend via Web conference (GoToMeeting). It is guided by OGC staff and sponsors and allows participants to exchange ideas. The main purpose is to refine the Hackathon architecture and settle upon specific interface models to be used as a baseline for prototype component interoperability. Participants will be *_required_* to attend the Kickoff either in person or by Web conference.

*Decision Conference:* Conducted one week after the kick-off meeting, the Decision Conference web conference will decide any outstanding design decisions from the kick-off meeting. It is the conference with all participants prior to the _Preparation Conference._

After the Decision Conference, all Hackathon activities will be conducted remotely. Communication overhead is reduced to email-list discussions.

*Preparation Conference:* This webinar discusses details for the _Demonstration Meeting._

[[demonstration_workshop]]
*Demonstration Workshop:* Physical meeting, where participants demonstrate their results.
```

In the same file:
```adoc
[[policies_procedures]]
==== Hackathon Implementation

[[hackaton_scenario]]
*Scenario*

The Hackathon shall implement the following scenario:
```

**Comment by opoudjis** [comment]
Ronald, OF COURSE there is a label issue. 

Yes, we can have a crossreference pointing to a paragraph. But we have not defined a label for random paragraphs in Metanorma, the way we have for other cross-references: Metanorma has no notion of saying "Section X, paragraph 4", and nor should it. In fact, I'm struggling to think what label you could meaningfully automate there.

Of course, the crossreference to the paragraph is populated with your suggested text. So perhaps I should not report on labelling issues unless there is a cross-reference to them which expects an auto-populated label. Let me check the rest of these issues...

**Comment by opoudjis** [comment]
> The second document has anchors set on paragraphs, but they're not carried to the XML.

Not true: document.xml has:

> `<p id="demonstration_workshop"><strong>Demonstration Workshop:</strong> Physical meeting, where participants demonstrate their results.</p>`
> `<p id="kickoff_workshop"><strong>Kickoff Workshop:</strong>`
> `<p id="hackaton_scenario"><strong>Scenario</strong>

The error report is intended for failures of automated labelling to generate a label for an anchor, whether or not that label is used: they are meant for tables or figures whose autonumbering has gone dodgy. They have nothing meaningful to do with paragraphs, which are being labelled correctly, and cross-referenced correctly (because you've populated the cross-reference text).

... Yeah, I can see that the user does not need to be alerted about missing autolabels if those autolabels are never used.

**Comment by opoudjis** [comment]
In the first document, by contrast, the IDs for requirements are indeed being ignored. (That's what you said was happening for the second document.)

**Comment by opoudjis** [comment]
Woah. I was indeed completely ignoring the IDs on requirements in markup. That's getting fixed now.

**Comment by opoudjis** [comment]
With that fix, the dozens of missing ID labels in 17-069r3 have gone down to just "rc_geojson". That anchor was in fact missing from the document, and I'm inserting it.

**Comment by opoudjis** [comment]
It turns out there's poor logic flow in isodoc: the autolink is generated, complete with error message, before the textual content of the crossreference is parsed, to check whether the autolink is needed at all. Fixing.

**Comment by opoudjis** [comment]
Aaaand label warnings from 18-046 have now disappeared.
